name: Publish Docs

on:  
  push:
    branches: [ master ]
    paths:
    - 'docs'

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout gh-pages
      uses: actions/checkout@v2
      with:
        ref: gh-pages
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
    - name: Build
      run: |
        cd docs
        make html
        python deploy.py
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.0.0
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: _web # The folder the action should deploy.
